// src/app/components/elements/navigation.vue
<template>
    <el-menu
            :default-active="activeIndex"
            class="el-menu-demo"
            mode="horizontal"
            active-text-color="#ffd04b"
            background-color="#ffffff"
            :router="true"
    >
        <el-menu-item :index="constants.PAGE_PATH.BASE.path">
            <span>Главная</span>
        </el-menu-item>
        <el-menu-item :index="constants.PAGE_PATH.DELIVERY_POINT.ALL.path">
            <i class="el-icon-rank"></i>
            <span>Пункты отправки / доставки</span>
        </el-menu-item>
        <el-menu-item :index="constants.PAGE_PATH.CUSTOMER.ALL.path">
            <i class="el-icon-star-on"></i>
            <span>Клиенты</span>
        </el-menu-item>
        <el-menu-item :index="constants.PAGE_PATH.ORDER.ALL.path">
            <i class="el-icon-document"></i>
            <span>Заказы</span>
        </el-menu-item>
        <el-submenu index="" class="right">
            <template slot="title">
                <i class="el-icon-more"></i>
                <span>{{currentUser().name}}</span>
            </template>
            <el-menu-item index="" @click="logout">Выход</el-menu-item>
        </el-submenu>
    </el-menu>
</template>

<script lang="ts">
    /*
     * ©  Implicitly86 All Rights Reserved
     */

    import { Component, Vue } from "vue-property-decorator";
    import * as jwtDecode from 'jwt-decode';

    import { Constants } from "../../constants/common_constants";
    import { User } from "../../models/user";
    import { DecodedToken } from "../../models/decoded_token";
    import { router } from "../../router/router";

    /**
     * Компонент, отвечающий за навигацию в приложении.
     *
     * @author Emil Murzakaev.
     */
    @Component({
        name: 'navigation',
        props: {
            activeIndex: {
                type: String,
                default: Constants.PAGE_PATH.BASE.path
            }
        }
    })
    export default class Navigation extends Vue {

        /**
         * Текущий залогиненный пользователь.
         */
        private user: User;
        /**
         * Константы, используемые в приложении.
         */
        private constants = Constants;

        /**
         * Конструктор.
         */
        constructor() {
            super();
            let decodedToken: DecodedToken = jwtDecode<DecodedToken>(localStorage.getItem(Constants.AUTH.TOKEN_NAME)!);
            this.user = DecodedToken.getUser(decodedToken);
        }

        /**
         * Получить текущего залогиненного пользователя.
         *
         * @return текущий залогиненный пользователь.
         */
        public currentUser(): User {
            return this.user;
        }

        /**
         * Выход из приложения.
         */
        public logout() {
            localStorage.removeItem(Constants.AUTH.TOKEN_NAME);
            router.push({path: Constants.PAGE_PATH.LOGIN.path});
        }

    }
</script>

<style scoped>
    a {
        text-decoration: none;
    }

    .right {
        float: right;
        margin-right: 10px;
    }
</style>

// src/app/components/elements/navigation.tsx
/*
 * ©  Implicitly86 All Rights Reserved
 */

import * as React from "react";
import {Link} from 'react-router-dom'
import {Icon, Menu} from "antd";
// import "./nav.css";
import {Constants} from "../../constants/common_constants";
import {history} from "../../utils/history";

/**
 * Свойства компонента {@link Navigation}.
 */
interface NavigationProps {
    index: string;
}

/**
 * Компонент, реализующий навигацию в приложении.
 *
 * @author Emil Murzakaev.
 */
export class Navigation extends React.Component<NavigationProps, any> {

    /**
     * Обработка нажатия.
     */
    private handleClick = (e) => {
        if (e.key === 'logout') {
            localStorage.removeItem(Constants.AUTH.TOKEN_NAME);
            history.push(Constants.PAGE_PATH.LOGIN.path);
        }
    };

    /**
     * Функция рендеринга компонента.
     */
    render() {
        return (
            <Menu selectedKeys={[this.props.index]} mode="horizontal" onClick={this.handleClick} className="navigation">
                <Menu.Item key={Constants.PAGE_PATH.DELIVERY_POINT.ALL.name}>
                    <Link to={Constants.PAGE_PATH.DELIVERY_POINT.ALL.path}>
                        <Icon type="arrows-alt"/>Пункты отправки / доставки
                    </Link>
                </Menu.Item>
                <Menu.Item key={Constants.PAGE_PATH.CUSTOMER.ALL.name}>
                    <Link to={Constants.PAGE_PATH.CUSTOMER.ALL.path}>
                        <Icon type="user" theme="outlined"/>Клиенты
                    </Link>
                </Menu.Item>
                <Menu.Item key={Constants.PAGE_PATH.ORDER.ALL.name}>
                    <Link to={Constants.PAGE_PATH.ORDER.ALL.path}>
                        <Icon type="shopping" theme="outlined"/>Заказы
                    </Link>
                </Menu.Item>
                <Menu.Item key="logout" className="last_item">
                    <Icon type="logout" theme="outlined"/>Выход
                </Menu.Item>
            </Menu>
        );
    }

}
