// src/app/components/app.vue
<template>
    <router-view class="view content"></router-view>
</template>

<script lang="ts">
    /*
     * ©  Implicitly86 All Rights Reserved
     */

    import { Component, Vue } from "vue-property-decorator";
    import * as schedule from "node-schedule";
    import * as jwtDecode from 'jwt-decode';

    import { DecodedToken } from "../models/decoded_token";
    import { router } from "../router/router";
    import { Constants } from "../constants/common_constants";

    /**
     * Основной компонент приложения.
     *
     * @author Emil Murzakaev.
     */
    @Component
    export default class App extends Vue {

        constructor() {
            super();
            schedule.scheduleJob('checkTokenExpiration', '*/1 * * * *', () => {
                let currentRoute = router.currentRoute.name!;
                if (localStorage.getItem(Constants.AUTH.TOKEN_NAME) != null && currentRoute != Constants.PAGE_PATH.LOGIN.name) {
                    let decodedToken: DecodedToken = jwtDecode(localStorage.getItem(Constants.AUTH.TOKEN_NAME)!);
                    let currentDateTime = new Date().getTime();
                    let expireDateTime = decodedToken.exp * 1000;
                    if ((expireDateTime - currentDateTime) / 1000 < 60) {
                        localStorage.removeItem(Constants.AUTH.TOKEN_NAME);
                        router.push({path: Constants.PAGE_PATH.LOGIN.path, query: {'redirect': currentRoute}});
                    }
                }
            });
        }

    }

</script>

<style scoped></style>

// src/app/components/app.tsx
/*
 * ©  Implicitly86 All Rights Reserved
 */

import * as React from "react";
import {Route, Router} from 'react-router-dom'

import {history} from '../utils/history';
import {Constants} from "../constants/common_constants";
import {Login} from "./pages/login/login";
import {DeliveryPoint} from "./pages/delivery_point/delivery_point";
import {Customer} from "./pages/customer/customer";
import {Order} from "./pages/order/order";

/**
 * Компонент приложения.
 *
 * @author Emil Murzakaev.
 */
export class App extends React.Component<any, any> {

    /**
     * Функция рендеринга компонента.
     */
    render() {
        return (
            <Router history={history}>
                <div>
                    <Route exact path={Constants.PAGE_PATH.BASE.path} component={DeliveryPoint}/>
                    <Route path={Constants.PAGE_PATH.LOGIN.path} component={Login}/>
                    <Route path={Constants.PAGE_PATH.DELIVERY_POINT.ALL.path} component={DeliveryPoint}/>
                    <Route path={Constants.PAGE_PATH.CUSTOMER.ALL.path} component={Customer}/>
                    <Route path={Constants.PAGE_PATH.ORDER.ALL.path} component={Order}/>
                </div>
            </Router>
        );
    }

}
